### ISSUE TITLE
angular

### ISSUE THREAD

**Issue by XiaoYunhan** [XiaoYunhan/Temp#1]
<div class="rules-container">
  <div class="header-section">
    <h2>Rules and Regulations</h2>
    <div class="action-buttons">
      <button (click)="selectAll()">Select All</button>
      <button (click)="unselectAll()">Unselect All</button>
    </div>
  </div>
  
  <div class="rules-checkbox-list">
    <div class="checkbox-columns-container">
      <div *ngFor="let column of columns" class="checkbox-column">
        <div class="column-header" (click)="toggleColumn(column)">
          <div class="header-content">
            <input
              *ngIf="column.headerCheckbox"
              type="checkbox"
              class="header-checkbox"
              [(ngModel)]="column.headerChecked"
              [indeterminate]="column.headerIndeterminate"
              (change)="onHeaderCheckboxChange(column)"
              (click)="$event.stopPropagation()"
            />
            <span class="column-title">{{ column.title }}</span>
          </div>
          <span *ngIf="column.canCollapse" class="collapse-icon">
            <svg
              [class.rotated]="column.isCollapsed"
              width="10"
              height="6"
              viewBox="0 0 10 6"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M1 1L5 5L9 1"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </span>
        </div>
        
        <div class="checkbox-items" [class.collapsed]="column.isCollapsed">
          <ng-container *ngFor="let item of column.items">
            <div class="checkbox-item" [class.has-children]="item.hasChildren">
              <span 
                *ngIf="item.hasChildren" 
                class="expand-icon"
                [class.expanded]="item.isExpanded"
                (click)="toggleSubItems(item)"
              >
                <svg width="8" height="8" viewBox="0 0 8 8" fill="none">
                  <path d="M1 3L4 6L7 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
              </span>
              <div class="checkbox-wrapper">
                <input
                  type="checkbox"
                  [id]="column.id + '-' + item.id"
                  [(ngModel)]="item.checked"
                  (change)="item.hasChildren ? onParentCheckboxChange(item) : onItemCheckboxChange(column, item)"
                />
                <label [for]="column.id + '-' + item.id">{{ item.label }}</label>
              </div>
            </div>
            
            <ng-container *ngIf="item.children && item.isExpanded">
              <div
                *ngFor="let child of item.children"
                class="checkbox-item indented"
              >
                <div class="checkbox-wrapper">
                  <input
                    type="checkbox"
                    [id]="column.id + '-' + child.id"
                    [(ngModel)]="child.checked"
                    (change)="onItemCheckboxChange(column, child)"
                  />
                  <label [for]="column.id + '-' + child.id">{{ child.label }}</label>
                </div>
              </div>
            </ng-container>
          </ng-container>
        </div>
      </div>
    </div>
  </div>
</div>

.rules-container {
  max-width: 1400px;
  margin: 0 auto;
}

.header-section {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding: 0 16px;

  h2 {
    margin: 0;
    font-size: 20px;
    color: #24292f;
  }
}

.action-buttons {
  display: flex;
  gap: 12px;

  button {
    padding: 6px 16px;
    border: 1px solid #d1d5da;
    background-color: white;
    border-radius: 6px;
    font-size: 14px;
    cursor: pointer;
    transition: all 0.2s;
    color: #24292f;

    &:hover {
      background-color: #f6f8fa;
      border-color: #0969da;
    }
  }
}

.rules-checkbox-list {
  padding: 16px;
  background-color: #f8f9fa;
  border-radius: 4px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  font-size: 13px;
  color: #333;
}

.checkbox-columns-container {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 16px;

  @media (max-width: 1200px) {
    grid-template-columns: repeat(3, 1fr);
  }

  @media (max-width: 768px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 480px) {
    grid-template-columns: 1fr;
  }
}

.checkbox-column {
  background-color: white;
  border: 1px solid #e1e4e8;
  border-radius: 4px;
  overflow: hidden;
}

.column-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background-color: #f6f8fa;
  border-bottom: 1px solid #e1e4e8;
  cursor: pointer;
  user-select: none;
  transition: background-color 0.2s;
  min-height: 40px;

  &:hover {
    background-color: #e9ecef;
  }
}

.header-content {
  display: flex;
  align-items: center;
  gap: 8px;
}

.header-checkbox {
  cursor: pointer;
}

.column-title {
  font-weight: 600;
  font-size: 14px;
  color: #24292f;
}

.collapse-icon {
  display: flex;
  align-items: center;
  color: #57606a;
  transition: transform 0.2s;

  svg {
    transition: transform 0.2s;
    
    &.rotated {
      transform: rotate(-90deg);
    }
  }
}

.checkbox-items {
  max-height: 400px;
  overflow-y: auto;
  transition: max-height 0.3s ease-out;
  
  &.collapsed {
    max-height: 0;
    overflow: hidden;
  }
}

.checkbox-item {
  display: flex;
  align-items: center;
  padding: 10px 24px;
  border-bottom: 1px solid #f0f0f0;
  transition: background-color 0.2s;
  position: relative;

  &:last-child {
    border-bottom: none;
  }

  &:hover {
    background-color: #f8f9fa;
  }

  &.has-children {
    cursor: pointer;
  }

  &.indented {
    padding-left: 48px;

    &::before {
      content: '';
      position: absolute;
      left: 24px;
      top: 50%;
      width: 16px;
      height: 1px;
      background-color: #d1d5da;
    }
  }
}

.expand-icon {
  position: absolute;
  left: 8px;
  top: 50%;
  transform: translateY(-50%);
  color: #57606a;
  cursor: pointer;
  display: flex;
  align-items: center;

  svg {
    transition: transform 0.2s;
  }

  &.expanded svg {
    transform: rotate(90deg);
  }
}

.checkbox-wrapper {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
}

// Custom checkbox styling
input[type="checkbox"] {
  width: 16px;
  height: 16px;
  border: 1px solid #d1d5da;
  border-radius: 3px;
  background-color: white;
  appearance: none;
  cursor: pointer;
  position: relative;
  transition: all 0.2s;
  margin: 0;
  flex-shrink: 0;

  &:checked {
    background-color: #0969da;
    border-color: #0969da;

    &::after {
      content: '';
      position: absolute;
      left: 5px;
      top: 2px;
      width: 4px;
      height: 8px;
      border: solid white;
      border-width: 0 2px 2px 0;
      transform: rotate(45deg);
    }
  }

  &:hover:not(:checked) {
    border-color: #0969da;
  }

  &:indeterminate {
    background-color: #0969da;
    border-color: #0969da;

    &::after {
      content: '';
      position: absolute;
      left: 3px;
      top: 6px;
      width: 10px;
      height: 2px;
      background-color: white;
      transform: none;
      border: none;
    }
  }
}

label {
  cursor: pointer;
  line-height: 1.4;
  color: #24292f;
  margin: 0;
}

// Scrollbar styling
.checkbox-items {
  &::-webkit-scrollbar {
    width: 8px;
  }

  &::-webkit-scrollbar-track {
    background: #f1f1f1;
  }

  &::-webkit-scrollbar-thumb {
    background: #c1c1c1;
    border-radius: 4px;

    &:hover {
      background: #a8a8a8;
    }
  }
}

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface CheckboxItem {
  id: string;
  label: string;
  checked: boolean;
  hasChildren?: boolean;
  isExpanded?: boolean;
  parentId?: string;
  children?: CheckboxItem[];
}

interface CheckboxColumn {
  id: string;
  title: string;
  canCollapse: boolean;
  isCollapsed: boolean;
  items: CheckboxItem[];
  headerCheckbox?: boolean;
  headerChecked?: boolean;
  headerIndeterminate?: boolean;
}

@Component({
  selector: 'app-rules-checkbox-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './rules-checkbox-list.component.html',
  styleUrls: ['./rules-checkbox-list.component.scss']
})
export class RulesCheckboxListComponent {
  @Input() columns: CheckboxColumn[] = [];
  @Output() selectionChange = new EventEmitter<any>();

  ngOnInit() {
    // Initialize with sample data if no input provided
    if (this.columns.length === 0) {
      this.columns = this.getSampleData();
    }
  }

  toggleColumn(column: CheckboxColumn): void {
    if (column.canCollapse) {
      column.isCollapsed = !column.isCollapsed;
    }
  }

  onHeaderCheckboxChange(column: CheckboxColumn): void {
    if (column.headerCheckbox && column.headerChecked !== undefined) {
      // Check/uncheck all items in the column
      column.items.forEach(item => {
        item.checked = column.headerChecked!;
        if (item.children) {
          item.children.forEach(child => child.checked = column.headerChecked!);
        }
      });
      this.emitSelectionChange();
    }
  }

  onItemCheckboxChange(column: CheckboxColumn, item: CheckboxItem): void {
    // If parent item, update children
    if (item.hasChildren && item.children) {
      item.children.forEach(child => child.checked = item.checked);
    }
    
    // Update header checkbox state
    this.updateHeaderStates();
    this.emitSelectionChange();
  }

  private emitSelectionChange(): void {
    const selection = this.columns.map(column => {
      const selectedItems: CheckboxItem[] = [];
      column.items.forEach(item => {
        if (item.checked) selectedItems.push(item);
        if (item.children) {
          selectedItems.push(...item.children.filter(child => child.checked));
        }
      });
      return {
        columnId: column.id,
        title: column.title,
        selectedItems
      };
    });
    this.selectionChange.emit(selection);
  }

  selectAll(): void {
    this.columns.forEach(column => {
      if (column.headerCheckbox) {
        column.headerChecked = true;
      }
      column.items.forEach(item => {
        item.checked = true;
        if (item.children) {
          item.children.forEach(child => child.checked = true);
        }
      });
    });
    this.updateHeaderStates();
    this.emitSelectionChange();
  }

  unselectAll(): void {
    this.columns.forEach(column => {
      if (column.headerCheckbox) {
        column.headerChecked = false;
      }
      column.items.forEach(item => {
        item.checked = false;
        if (item.children) {
          item.children.forEach(child => child.checked = false);
        }
      });
    });
    this.updateHeaderStates();
    this.emitSelectionChange();
  }

  toggleSubItems(item: CheckboxItem): void {
    if (item.hasChildren) {
      item.isExpanded = !item.isExpanded;
    }
  }

  onParentCheckboxChange(parentItem: CheckboxItem): void {
    if (parentItem.children) {
      parentItem.children.forEach(child => {
        child.checked = parentItem.checked;
      });
    }
    this.emitSelectionChange();
  }

  private updateHeaderStates(): void {
    this.columns.forEach(column => {
      if (column.headerCheckbox) {
        const allItems = this.getAllItemsInColumn(column);
        const allChecked = allItems.every(item => item.checked);
        const someChecked = allItems.some(item => item.checked);
        
        column.headerChecked = allChecked;
        column.headerIndeterminate = someChecked && !allChecked;
      }
    });
  }

  private getAllItemsInColumn(column: CheckboxColumn): CheckboxItem[] {
    const allItems: CheckboxItem[] = [];
    column.items.forEach(item => {
      allItems.push(item);
      if (item.children) {
        allItems.push(...item.children);
      }
    });
    return allItems;
  }

  private getSampleData(): CheckboxColumn[] {
    return [
      {
        id: 'client-readiness',
        title: 'Client Readiness',
        canCollapse: true,
        isCollapsed: false,
        headerCheckbox: true,
        headerChecked: false,
        items: [
          { id: 'aml-kyc', label: 'AML/KYC', checked: false },
          { id: 'lei', label: 'LEI', checked: false }
        ]
      },
      {
        id: 'trading-profile',
        title: 'Trading Profile',
        canCollapse: true,
        isCollapsed: false,
        headerCheckbox: true,
        headerChecked: false,
        items: [
          { id: 'equities', label: 'Equities', checked: false },
          { 
            id: 'ficc', 
            label: 'FICC', 
            checked: false,
            hasChildren: true,
            isExpanded: false,
            children: [
              { id: 'terms-business', label: 'Terms Of Business', checked: false, parentId: 'ficc' },
              { id: 'mifid-classification', label: 'MiFID II Classification', checked: false, parentId: 'ficc' },
              { id: 'best-execution', label: 'Best Execution', checked: false, parentId: 'ficc' }
            ]
          },
          { id: 'local-authority', label: 'Local Authority Opt-Up', checked: false },
          { 
            id: 'futures-options', 
            label: 'Futures & Options', 
            checked: false,
            hasChildren: true,
            isExpanded: false,
            children: [
              { id: 'futures-options-exec', label: 'Futures & Options Execution', checked: false, parentId: 'futures-options' },
              { id: 'futures-options-clearing', label: 'Futures & Options Clearing', checked: false, parentId: 'futures-options' }
            ]
          },
          { id: 'emir-classification', label: 'EMIR Classification', checked: false },
          { id: 'emir-corporate', label: 'EMIR Corporate Sector', checked: false }
        ]
      },
      {
        id: 'global-stay-protocols',
        title: 'Global Stay Protocols',
        canCollapse: true,
        isCollapsed: false,
        headerCheckbox: false,
        items: [
          { id: 'french-resolution', label: 'French Resolution Stay', checked: false },
          { id: 'uk-resolution', label: 'UK Resolution Stay', checked: false },
          { id: 'us-resolution', label: 'US Resolution Stay', checked: false },
          { id: 'irish-resolution', label: 'Irish Resolution Stay', checked: false },
          { id: 'japan-resolution', label: 'Japan Resolution Stay', checked: false }
        ]
      },
      {
        id: 'regulatory-margin',
        title: 'Regulatory Margin Rules',
        canCollapse: true,
        isCollapsed: false,
        headerCheckbox: false,
        items: [
          { id: 'umr', label: 'UMR', checked: false },
          { id: 'umr-pb', label: 'UMR PB', checked: false },
          { id: 'sec-sbs-isda', label: 'Sec SBS ISDA Master Agreement', checked: false },
          { id: 'segregation-initial', label: 'Segregation Initial Margin Notice', checked: false },
          { id: 'sec-umr', label: 'SEC UMR', checked: false },
          { id: 'sec-sbs-umr-vm', label: 'SEC SBS UMR Reg VM Adherence', checked: false },
          { id: 'sec-sbs-umr-im', label: 'SEC SBS UMR Reg IM Adherence', checked: false },
          { id: 'eu-benchmark', label: 'EU Benchmark Regulation', checked: false }
        ]
      },
      {
        id: 'global-reporting',
        title: 'Global Reporting Consent (GCOC)',
        canCollapse: true,
        isCollapsed: false,
        headerCheckbox: false,
        items: [
          { id: 'mifid-reporting', label: 'MiFID Reporting Consent', checked: false },
          { id: 'emir-reporting', label: 'EMIR Reporting Consent', checked: false },
          { id: 'sftr', label: 'SFTR', checked: false },
          { id: 'cftc-reporting', label: 'CFTC Reporting Consent', checked: false },
          { id: 'sec-sbs-reporting', label: 'SEC SBS Reporting Consent', checked: false },
          { id: 'canada-reporting', label: 'Canada Reporting Consent', checked: false },
          { id: 'hkma', label: 'HKMA', checked: false },
          { id: 'asic', label: 'ASIC', checked: false },
          { id: 'israel', label: 'Israel', checked: false },
          { id: 'nccbr', label: 'NCCBR', checked: false }
        ]
      },
      {
        id: 'external-business',
        title: 'External Business Conduct Rules',
        canCollapse: true,
        isCollapsed: false,
        headerCheckbox: false,
        items: [
          { id: 'cftc', label: 'CFTC', checked: false },
          { id: 'sec-sbs', label: 'Sec SBS', checked: false },
          { id: 'canada', label: 'Canada', checked: false },
          { id: 'emir', label: 'EMIR', checked: false },
          { id: 'emir-reporting-obligation', label: 'EMIR Reporting Obligation', checked: false },
          { id: 'mas-rmr', label: 'MAS RMR', checked: false },
          { id: 'finra-4210', label: 'FINRA 4210', checked: false },
          { id: 'hire-act', label: 'Hire Act', checked: false }
        ]
      }
    ];
  }
}

**Comment by XiaoYunhan** [comment]
```ts

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface CheckboxItem {
  id: string;
  label: string;
  checked: boolean;
  children?: CheckboxItem[];
  expanded?: boolean;
}

interface CheckboxColumn {
  id: string;
  title: string;
  collapsible?: boolean;
  collapsed?: boolean;
  hasSelectAll?: boolean;
  items: CheckboxItem[];
}

@Component({
  selector: 'app-rules-checkbox-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './rules-checkbox-list.component.html',
  styleUrls: ['./rules-checkbox-list.component.scss']
})
export class RulesCheckboxListComponent {
  @Input() columns: CheckboxColumn[] = [];
  @Output() selectionChange = new EventEmitter<any>();

  selectAll(): void {
    this.columns.forEach(col => {
      col.items.forEach(item => {
        item.checked = true;
        item.children?.forEach(child => child.checked = true);
      });
    });
    this.emitChange();
  }

  unselectAll(): void {
    this.columns.forEach(col => {
      col.items.forEach(item => {
        item.checked = false;
        item.children?.forEach(child => child.checked = false);
      });
    });
    this.emitChange();
  }

  toggleColumn(column: CheckboxColumn): void {
    if (column.collapsible) {
      column.collapsed = !column.collapsed;
    }
  }

  toggleAllInColumn(column: CheckboxColumn, checked: boolean): void {
    column.items.forEach(item => {
      item.checked = checked;
      item.children?.forEach(child => child.checked = checked);
    });
    this.emitChange();
  }

  toggleItem(item: CheckboxItem): void {
    if (item.children) {
      item.children.forEach(child => child.checked = item.checked);
    }
    this.emitChange();
  }

  toggleExpand(item: CheckboxItem): void {
    if (item.children) {
      item.expanded = !item.expanded;
    }
  }

  isColumnIndeterminate(column: CheckboxColumn): boolean {
    const items = column.items.flatMap(item => [item, ...(item.children || [])]);
    const checkedCount = items.filter(item => item.checked).length;
    return checkedCount > 0 && checkedCount < items.length;
  }

  isColumnChecked(column: CheckboxColumn): boolean {
    const items = column.items.flatMap(item => [item, ...(item.children || [])]);
    return items.length > 0 && items.every(item => item.checked);
  }

  private emitChange(): void {
    this.selectionChange.emit(this.columns);
  }
}
```

```html

<div class="rules-container">
  <div class="header">
    <h2>Rules and Regulations</h2>
    <div class="actions">
      <button (click)="selectAll()">Select All</button>
      <button (click)="unselectAll()">Unselect All</button>
    </div>
  </div>
  
  <div class="columns-grid">
    <div *ngFor="let column of columns" class="column">
      <div class="column-header" (click)="toggleColumn(column)">
        <div class="header-left">
          <input *ngIf="column.hasSelectAll"
                 type="checkbox"
                 [checked]="isColumnChecked(column)"
                 [indeterminate]="isColumnIndeterminate(column)"
                 (click)="$event.stopPropagation()"
                 (change)="toggleAllInColumn(column, $event.target.checked)">
          <span>{{ column.title }}</span>
        </div>
        <svg *ngIf="column.collapsible" 
             class="arrow" 
             [class.collapsed]="column.collapsed"
             width="10" height="6" viewBox="0 0 10 6">
          <path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5"/>
        </svg>
      </div>
      
      <div class="column-items" [class.collapsed]="column.collapsed">
        <ng-container *ngFor="let item of column.items">
          <div class="item">
            <svg *ngIf="item.children" 
                 class="expand-arrow"
                 [class.expanded]="item.expanded"
                 (click)="toggleExpand(item)"
                 width="8" height="8" viewBox="0 0 8 8">
              <path d="M1 3L4 6L7 3" stroke="currentColor" stroke-width="1.5"/>
            </svg>
            <input type="checkbox" 
                   [(ngModel)]="item.checked" 
                   (change)="toggleItem(item)">
            <label>{{ item.label }}</label>
          </div>
          
          <div *ngIf="item.expanded && item.children" class="children">
            <div *ngFor="let child of item.children" class="item child">
              <input type="checkbox" 
                     [(ngModel)]="child.checked" 
                     (change)="emitChange()">
              <label>{{ child.label }}</label>
            </div>
          </div>
        </ng-container>
      </div>
    </div>
  </div>
</div>
```

```scss

.rules-container {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  font-size: 13px;
  color: #333;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  
  h2 {
    margin: 0;
    font-size: 20px;
  }
  
  .actions button {
    padding: 6px 16px;
    margin-left: 12px;
    border: 1px solid #d1d5da;
    background: white;
    border-radius: 6px;
    cursor: pointer;
    
    &:hover {
      background: #f6f8fa;
      border-color: #0969da;
    }
  }
}

.columns-grid {
  display: flex;
  gap: 16px;
  background: #f8f9fa;
  padding: 16px;
  border-radius: 4px;
}

.column {
  flex: 1;
  background: white;
  border: 1px solid #e1e4e8;
  border-radius: 4px;
  overflow: hidden;
}

.column-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background: #f6f8fa;
  border-bottom: 1px solid #e1e4e8;
  cursor: pointer;
  
  &:hover {
    background: #e9ecef;
  }
  
  .header-left {
    display: flex;
    align-items: center;
    gap: 8px;
    
    span {
      font-weight: 600;
      font-size: 14px;
    }
  }
  
  .arrow {
    transition: transform 0.2s;
    &.collapsed {
      transform: rotate(-90deg);
    }
  }
}

.column-items {
  transition: max-height 0.3s;
  &.collapsed {
    display: none;
  }
}

.item {
  display: flex;
  align-items: center;
  padding: 10px 24px;
  border-bottom: 1px solid #f0f0f0;
  position: relative;
  
  &:last-child {
    border-bottom: none;
  }
  
  &:hover {
    background: #f8f9fa;
  }
  
  &.child {
    padding-left: 48px;
    
    &::before {
      content: '';
      position: absolute;
      left: 24px;
      top: 50%;
      width: 16px;
      height: 1px;
      background: #d1d5da;
    }
  }
  
  .expand-arrow {
    position: absolute;
    left: 8px;
    cursor: pointer;
    transition: transform 0.2s;
    
    &.expanded {
      transform: rotate(90deg);
    }
  }
  
  input[type="checkbox"] {
    width: 16px;
    height: 16px;
    margin-right: 8px;
    cursor: pointer;
  }
  
  label {
    cursor: pointer;
    line-height: 1.4;
  }
}

.children {
  .item:last-child {
    border-bottom: 1px solid #f0f0f0;
  }
}

// Responsive
@media (max-width: 1200px) {
  .columns-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
  }
}

@media (max-width: 768px) {
  .columns-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 480px) {
  .columns-grid {
    grid-template-columns: 1fr;
  }
  
  .header {
    flex-direction: column;
    gap: 12px;
    align-items: flex-start;
  }
}
```
